### ISSUE TITLE
question about predict_start_from_noise

### ISSUE THREAD

**Issue by gyy456** [BIRD-TAO/GNTPP#2]
```python
"sqrt_recip_alphas_cumprod", to_torch(np.sqrt(1.0 / alphas_cumprod)
"sqrt_recipm1_alphas_cumprod", to_torch(np.sqrt(1-alphas_cumprod/alphas_cumprod ))
``` 

```python
    def predict_start_from_noise(self, x_t, t, noise):
        return (
            extract(self.sqrt_recip_alphas_cumprod, t, x_t.shape) * x_t
            - extract(self.sqrt_recipm1_alphas_cumprod, t, x_t.shape) * noise
        )
``` 
in this code it means:

$$ 
x_0=\frac{x_t}{\sqrt{\bar{a}_t}}-\frac{1}{\sqrt{1-\bar{a}}}\varepsilon
$$

but in diffusion  models we know this

$$
x_t(x_0,\varepsilon)=\sqrt{\bar{a}_t}x_0+\sqrt{1-\bar{a}}\varepsilon ----->  x_0=\frac{x_t}{\sqrt{\bar{a}_t}}-\frac{\sqrt{1-\bar{a}_t}}{\sqrt{\bar{a}_t}}\varepsilon 
$$

so how to understand this problem?

**Comment by EDAPINENUT** [comment]
There are lots of noise schedules in DDPM, and the selected one is originally copied by the DDPM source code. You can refer more from the GitHub: https://github.com/hojonathanho/diffusion

**Comment by EDAPINENUT** [comment]
Besides, it is a function called predict_start_from_noise, which is the inverse process. I believe the equation
![image](https://user-images.githubusercontent.com/39732724/229369443-430fcf5e-f5c8-40e2-ac8f-b21f60fc574b.png)
may solve your problem. However, for more details, the given GitHub repository will give answers.

**Comment by EDAPINENUT** [comment]
Fixed.
