### ISSUE TITLE
Wrong splitting of embeddings.

### ISSUE THREAD

**Issue by davecasp** [BIRD-TAO/GNTPP#3]
https://github.com/BIRD-TAO/GNTPP/blob/2d67284d638882555a69f4e74d8dd90fd10cca5f/models/tpp_warper.py#L76

I think you mixed up the indexing of the type embedding.

**Comment by EDAPINENUT** [comment]
Thanks, we will change it very soon.
As the function is only used for similarity calculation, it does not affect the metric reported.

**Comment by EDAPINENUT** [comment]
It is fixed.
